// flow-typed signature: 54b6aaad657fba805448daee6c9aefe7
// flow-typed version: <<STUB>>/watchr_v^3.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'watchr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'watchr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'watchr/es2015/index' {
  declare module.exports: any;
}

declare module 'watchr/source/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'watchr/es2015/index.js' {
  declare module.exports: $Exports<'watchr/es2015/index'>;
}
declare module 'watchr/index' {
  declare module.exports: $Exports<'watchr'>;
}
declare module 'watchr/index.js' {
  declare module.exports: $Exports<'watchr'>;
}
declare module 'watchr/source/index.js' {
  declare module.exports: $Exports<'watchr/source/index'>;
}
