// flow-typed signature: 0b99c8a1c6ae7f5556f1d1f400f8737a
// flow-typed version: <<STUB>>/watcher_v0.0.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'watcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'watcher' {
  declare module.exports: any;
}
